import { ArrowRight, Clock3, MapPin, Search, Shirt, Soup, Tag, ToyBrick } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell, PageContainer, SectionHeading } from "../../components/AppShell";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";

const listings = [
  { title: "Assorted Organic Produce", category: "Food", location: "Greenwich Village, NY", availability: "4 bundles left", time: "2h left", icon: Soup, tone: "from-[#f4d59e] to-[#acd786]" },
  { title: "Premium Cotton Basics", category: "Clothing", location: "Chelsea, NY", availability: "12 items left", time: "1d left", icon: Shirt, tone: "from-[#d4e8ee] to-[#9bb9cf]" },
  { title: "Handcrafted Ceramic Set", category: "Household", location: "Williamsburg, BK", availability: "1 set left", time: "5h left", icon: Tag, tone: "from-[#efc4ad] to-[#d89173]" },
  { title: "Eco-Friendly Toy Set", category: "Kids & Toys", location: "Astoria, QNS", availability: "3 sets left", time: "3d left", icon: ToyBrick, tone: "from-[#f4d9a8] to-[#dd9574]" },
];
const categories = ["All Categories", "Food", "Clothing", "Household", "Kids & Toys"];
export const DonationMarketplace = (): JSX.Element => { const [category,setCategory]=useState("All Categories"); const [search,setSearch]=useState(""); const navigate=useNavigate(); const visible=listings.filter((item)=> (category === "All Categories" || item.category === category) && item.title.toLowerCase().includes(search.toLowerCase())); return <AppShell><PageContainer><SectionHeading eyebrow="Community marketplace" title="Sustainable Giving, Redefined." description="Browse high-quality donations from local neighbors and businesses. Keep useful items in circulation and out of landfills."/><div className="mx-auto flex max-w-3xl items-center rounded-2xl bg-white px-4 py-2 shadow-[inset_0_2px_8px_rgba(54,102,69,.08),0_8px_20px_rgba(54,102,69,.06)]"><Search size={18} className="text-[#8ca096]"/><Input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search for food, clothing, or household items..." className="h-11 border-0 bg-transparent shadow-none focus-visible:ring-0"/><Button className="rounded-full bg-[#27bb5c] px-5 font-bold text-white hover:bg-[#149b47]">Search</Button></div><div className="mt-8 flex flex-wrap justify-center gap-3">{categories.map((item)=><Button key={item} onClick={()=>setCategory(item)} className={`rounded-full px-5 py-2 font-semibold ${category === item ? "bg-[#34c759] text-[#064c20] hover:bg-[#34c759]" : "bg-white text-[#526158] hover:bg-[#e4f4e7]"}`}>{item}</Button>)}</div><div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{visible.map((item)=><article key={item.title} className="overflow-hidden rounded-[26px] bg-white shadow-[0_12px_30px_rgba(43,91,58,.1)] transition-transform hover:-translate-y-1"><div className={`relative flex h-52 items-center justify-center bg-gradient-to-br ${item.tone}`}><item.icon size={70} strokeWidth={1.2} className="text-white/80"/><span className="absolute right-4 top-4 rounded-full bg-white/85 px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-[#087532]">{item.category}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-extrabold">{item.title}</h2><span className="flex shrink-0 items-center gap-1 text-xs font-bold text-[#149449]"><Clock3 size={13}/>{item.time}</span></div><p className="mt-3 flex items-center gap-2 text-sm text-[#718077]"><MapPin size={15}/>{item.location}</p><div className="mt-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#9aa8a0]">Availability</p><p className="mt-1 text-sm font-bold">{item.availability}</p></div><Button onClick={()=>navigate('/donation-details')} className="rounded-full bg-[#27bb5c] px-5 font-bold text-white hover:bg-[#149b47]">Reserve <ArrowRight size={14}/></Button></div></div></article>)}</div>{visible.length===0 && <p className="py-16 text-center text-[#718077]">No donations match your search.</p>}</PageContainer></AppShell>; };
